require("plugins.plugins-setup")

require('plugins/commander')

require("core.options")
require("core.keymaps")

require("plugins.lualine")
require("plugins/nvim-tree")
require("plugins/treesitter")
require("plugins/lsp")
require("plugins/cmp")
require("plugins/comment")
require("plugins/autopairs")
require("plugins/bufferline")
require("plugins/gitsigns")
require("plugins/iconpick")
require("plugins/term")
require("plugins/telekasten") 
require("plugins/telescope")
require("plugins/iron")
require("plugins/markdown-preview")
require("plugins/claudecode")
